const { EmbedBuilder } = require('discord.js');

function seedRandom(seed) {
    let x = Math.sin(seed + 1) * 10000;
    return x - Math.floor(x);
}

function getHoroscopeForSign(signIndex, dateKey) {
    const horoscopes =
        [
        "Tu vas perdre une chaussette aujourd'hui. L'autre sera retrouvée en 2031.", "Mercure est en rétrograde dans ta salle de bain. Évite les miroirs.",
        "Un pigeon te regarde. Il sait.", "Ton destin est écrit sur un ticket de caisse Lidl froissé.", "Tu vas dire \"ah ouais\" à quelque chose d'important sans vraiment écouter.",
        "Quelqu'un pense à toi en ce moment. C'est flippant.", "Les astres disent : mange tes légumes. Les astres ont tort.",
        "Tu vas rater un truc important parce que t'étais sur TikTok.", "Venus est en opposition avec ta flemme. La flemme gagne.",
        "T'as un truc entre les dents depuis ce matin. Personne t'a rien dit.", "Ton futur est flou mais ça sent la friture.",
        "Tu vas avoir une révélation existentielle aux toilettes à 14h37.", "Quelqu'un va te dire \"on en reparlera\" et on en reparlera jamais.",
        "Les étoiles forment aujourd'hui la forme d'un kebab. C'est un signe.", "Tu vas trébucher sur rien et faire semblant que c'était fait exprès.",
        "Une opportunité se présente. T'as pas envie. Tu la rates. Bien joué.", "Ton chat te juge. Ton chat a raison.",
        "Tu vas recevoir un message vocal de 4 minutes pour une info qui tient en 5 mots.", "Saturne te dit d'aller dormir. T'iras à 4h du mat quand même.",
        "Ton aura est d'une couleur que personne a encore inventée. C'est inquiétant.", "Tu vas oublier ce que tu voulais dire en plein milieu d'une phrase et—",
        "Un inconnu va te sourire dans la rue. C'était pas pour toi.", "Tu vas retrouver 2€ dans une vieille veste. C'est tout ce que t'auras aujourd'hui.",
        "Mars est en colère. Mars a des raisons.", "Tu vas faire un truc bien par accident et prétendre que c'était prévu.",
        "Quelque part dans l'univers, une version de toi a pris la bonne décision. Pas toi.", "Tu vas rire à une blague que t'as pas comprise. C'est normal.",
        "Les planètes s'alignent pour te dire que t'aurais dû rappeler ta mère.", "Tu vas te battre mentalement contre quelqu'un dans ta tête et perdre.",
        "Une araignée dans ta chambre te surveille depuis 3 semaines. Elle note tout.", "Ton destin croise aujourd'hui celui d'un homme qui sent le jambon.",
        "Tu vas dire \"je suis crevé\" 7 fois sans bouger du canapé.", "L'univers te réserve une surprise. C'est nul.",
        "Tu vas mettre de la musique pour travailler et écouter de la musique.", "Quelqu'un va te demander \"tu vas bien ?\" avec le ton de quelqu'un qui s'en fout.",
        "Ton énergie du jour : pile suffisante pour survivre, pas assez pour briller.", "Tu vas relire un vieux message embarrassant à 2h du matin. Bonne nuit.",
        "Jupiter dit que t'as du potentiel. Jupiter ment.", "Tu vas commander trop de nourriture et manger trop de nourriture quand même.",
        "Ton signe est en harmonie avec le chaos total aujourd'hui. Bienvenue.", "Tu vas expliquer quelque chose très clairement et la personne va pas comprendre.",
        "Un truc que t'as dit il y a 6 ans va te revenir en mémoire sous la douche.", "Tu vas ouvrir le frigo 4 fois sans rien prendre. La 5ème fois non plus.",
        "L'astrologue qui a écrit ça était au fond de son lit en pyjama pingouin.", "Tu vas avoir raison sur quelque chose et personne t'écoutera.",
        "Mercure est en rétrograde depuis que t'es né(e). Ça explique tout.", "Tu vas envoyer un message au mauvais groupe. Encore.",
        "Les étoiles forment aujourd'hui un grand point d'interrogation juste au-dessus de ta tête.", "Tu vas procrastiner quelque chose d'important en lisant un horoscope.",
        "Ton avenir ressemble à un buffet froid où il reste que du chou-fleur.", "Tu vas rater ton réveil mais te lever à la seconde où tu te rendors.",
        "Quelqu'un va te demander de l'aide pour un truc et tu vas souffrir.", "Les astres te conseillent d'éviter les hommes en Crocs aujourd'hui.",
        "Tu vas avoir une conversation imaginaire très convaincante sous la douche.", "Ton énergie de la semaine : \"bof mais ça ira.\"",
        "Tu vas regarder ton téléphone sans raison précise exactement 47 fois aujourd'hui.", "Vénus dit que l'amour est proche. Vénus a aussi dit ça la semaine dernière.",
        "Tu vas faire quelque chose de stupide et l'appeler \"une expérience de vie\".", "Un enfant va te regarder avec trop d'intensité dans les transports. Il voit des trucs.",
        "Tu vas te rappeler d'une dette que tu dois mais choisir de l'oublier à nouveau.", "Ton horoscope du jour est classifié secret défense. Voilà ce qu'on peut dire : fais gaffe.",
        "Une lumière clignotera dans ton appart ce soir. C'est Morse pour \"aide-moi\".", "Tu vas commencer une phrase par \"non mais écoute\" et avoir tort.",
        "Les constellations forment aujourd'hui la silhouette de ton ex. Coïncidence ?", "Tu vas perdre un objet, paniquer, le retrouver dans ta main.",
        "Aujourd'hui tu vas mourir... de rire. Peut-être. On garantit rien.", "Ton chakra du bas est bloqué. Ton chakra du haut s'en fout.",
        "Tu vas mettre tes écouteurs, lancer un podcast, et penser à autre chose pendant 40 minutes.", "L'univers te souffle quelque chose à l'oreille. C'est incompréhensible.",
        "Tu vas dire \"je fais ça demain\" pour quelque chose que tu as dit hier.", "Un ami va te partager un meme que t'avais envoyé il y a 3 ans.",
        "Ton avenir est entre tes mains. Tes mains tremblent un peu. On s'inquiète.", "Les étoiles indiquent une journée productive. Les étoiles te connaissent pas.",
        "Tu vas avoir faim mais pas envie de cuisiner. Ce soir c'est céréales.", "Quelque chose de bizarre va se passer aujourd'hui et tu vas pas savoir quoi en penser.",
        "Tu vas souffrir en silence pour un truc complètement évitable.", "Mercure est en sextile avec ta flemme. Ça donne rien de bon.",
        "Tu vas dire \"c'est bon j'ai compris\" sans avoir compris.", "Les astres révèlent que tu lis cet horoscope alors que t'avais mieux à faire.",
        "Quelqu'un va te donner un conseil nul avec beaucoup de confiance.", "Tu vas être en retard pour quelque chose et arriver exactement à temps. Miracle.",
        "Ton avenir s'annonce… présent. C'est déjà ça.", "Tu vas croiser quelqu'un qui te ressemble dans la rue et ça va te perturber.",
        "Les planètes suggèrent que tu manges quelque chose de chaud. Les planètes ont raison pour une fois.",
        "Tu vas regarder une vidéo YouTube \"juste 5 minutes\" et réémerger 2 heures plus tard.", "Le cosmos a un plan pour toi. Le cosmos refuse de le divulguer.",
        "Tu vas expliquer un meme à quelqu'un et le tuer dans la foulée.", "Saturne rétrograde dans ta to-do list. Rien n'avance.",
        "Tu vas faire une bonne action aujourd'hui par pure erreur.", "Quelqu'un va dire ton prénom dans une conversation sans s'adresser à toi et tu vas quand même te retourner.",
        "Ton instinct te dit quelque chose. Ton instinct a souvent tort mais là peut-être pas.", "Tu vas avoir une idée géniale et l'oublier avant de la noter.",
        "Les astres indiquent une rencontre inoubliable. C'est un chien errant.", "Tu vas survivre à cette journée. Bravo. C'était pas garanti.",
        "Ton énergie du jour est \"fonctionne mais le voyant clignote\".", "Tu vas prendre une décision importante en mode \"on verra bien\".",
        "Une bonne nouvelle arrive. Elle est accompagnée d'une moins bonne nouvelle.", "Tu vas faire semblant d'avoir lu quelque chose que t'as pas lu.",
        "L'univers entier s'est aligné aujourd'hui pour que tu lises cet horoscope. C'était pas la peine.", "Les astres révèlent que t'as une gueule de bois cosmique. C'est mérité.",
        "Mercure est dans ta merde aujourd'hui. Littéralement.", "Tu vas te lever du mauvais pied, trébucher, et te faire chier la gueule. Bonne journée.",
        "L'univers t'envoie un message : va te faire foutre, mais avec amour.", "Ton chakra du cul est particulièrement actif aujourd'hui. Évite les chaises en plastique.",
        "Tu vas péter au mauvais moment. Les planètes étaient au courant.", "Saturne te dit d'aller niquer ta mère. Saturne est en colère ce matin.",
        "Tu vas te chier dessous de rire. Ou juste te chier dessous. Les astres sont flous là-dessus.", "Venus est en opposition avec ton cerveau. Ton cerveau perd.",
        "Tu vas dire une connerie monumentale avec une confiance absolue. Les étoiles applaudissent.", "Ton avenir pue. Pas métaphoriquement. Il pue vraiment.",
        "Un inconnu va te faire chier aujourd'hui. Tu pourras rien dire.", "Les constellations forment aujourd'hui un grand doigt d'honneur en ta direction.",
        "Tu vas rater quelque chose d'important parce que t'étais en train de te gratter les fesses.", "Mercure rétrograde dans tes couilles/ovaires. Ça explique tout.",
        "Tu vas envoyer un message à quelqu'un que t'aimes pas par accident. Merde.", "L'univers a décidé que tu te feras chier aujourd'hui. L'univers s'assume.",
        "Tu vas faire un pet silencieux dans un endroit très calme. Les gens sauront que c'est toi.", "Ton destin sent la transpiration et le kebab froid. C'est toi qui vois.",
        "Jupiter te dit d'aller dormir. Jupiter peut aller se faire mettre.", "Tu vas te coincer le zizi/les seins dans quelque chose d'improbable.",
        "Les étoiles révèlent que quelqu'un pense à toi en ce moment. C'est pour te dire que t'es con(ne).", "Ton aura est d'un brun douteux aujourd'hui. Très douteux.",
        "Tu vas lâcher un pet pendant une visio. Les astres avaient prévenu.", "Un truc de merde va t'arriver. Les planètes haussent les épaules.",
    "Tu vas essayer de faire une bonne impression et te vautrer comme une merde.", "Mercure dit que t'es un boulet cosmique. Mercure est honnête.",
    "Tu vas passer la journée à rien foutre et quand même être crevé(e). C'est un talent.", "Ton horoscope du jour : ça va être de la merde, mais courageusement.",
    "Les astres ont vu ce que t'as fait la semaine dernière. Ils jugent pas. Si.", "Tu vas te battre avec une imprimante et perdre. Comme toujours.",
    "Quelqu'un va te faire une remarque chiante et t'auras pas de répartie. Tu y penseras à 3h du mat.", "Ton avenir ressemble à un kebab tombé par terre. T'as encore faim quand même.",
    "Tu vas rater ton bus, ta correspondance, et ta vie. Bonne journée !", "Les planètes t'envoient de l'amour. L'amour arrive avec 3 semaines de retard comme toujours.",
    "Tu vas dire \"j'arrive\" et arriver 45 minutes plus tard. Les étoiles soupirent.", "Ton énergie du jour : \"je m'en bats les couilles mais poliment.\"",
    "Une flatulence inattendue va changer le cours de ta journée.", "Tu vas te lever pour rien, rester debout 3 secondes, et te rasseoir. Les astres compatissent.",
    "Vénus est dans ta zone de confort. Bouge-toi le cul quand même.", "Tu vas manger quelque chose qui va te faire regretter d'avoir un système digestif.",
    "Les étoiles te souhaitent une bonne journée. Les étoiles sont naïves.", "Quelqu'un va te faire chier avec ses problèmes alors que t'as les tiens.",
    "Ton karma du jour : moyen-moyen avec une pointe de \"va te faire voir\".", "Tu vas perdre 2 heures sur Internet pour rien. Sauf si t'en perdais 3 hier. Alors c'est du progrès.",
    "Mercure est en rétrograde dans tes toilettes. Mets le ventilateur.", "Les astres révèlent que quelqu'un a pété dans l'ascenseur avant toi. C'était pas beau.",
    "Tu vas avoir la flemme d'une intensité cosmique rarement observée.", "Ton signe est en dissonance avec tout. Absolument tout. Même ton IKEA.",
    "L'univers te dit merde mais avec un sourire. Ça change rien au fond.", "Tu vas te planter les doigts de pied sur un meuble et jurer comme un charretier.",
    "Les planètes s'alignent pour te signaler que t'es un cas désespéré. Mais attendrissant.", "Tu vas envoyer un message d'amour au mauvais contact. Bonne chance.",
    "Saturne dit que tu peux aller te rhabiller. Saturne a ses raisons.", "Ton avenir brille. C'est peut-être juste de la sueur. On démêle pas bien.",
    "Tu vas dire une connerie et la défendre jusqu'à la mort par orgueil.", "Les étoiles forment aujourd'hui le mot \"nul\" juste au-dessus de ta tête.",
    "Tu vas te réveiller avec une chanson chiante dans la tête qui partira pas de la journée.", "Quelque chose va mal tourner. T'avais été prévenu(e). Là. Maintenant.",
    "Les astres te souhaitent bonne chance. Les astres rigolent quand même un peu.", "Tu vas tenter un truc stylé et te gameler comme une patate.",
    "Mercure est en sextile avec ta mauvaise foi. Ça donne un truc immonde.", "Ton chakra du nombril parle. Personne l'écoute. Normal.",
    "Tu vas te faire chier pendant 3h sur un truc qui prend 10 minutes aux gens normaux.", "Les planètes révèlent que t'as besoin d'une douche. Maintenant.",
    "Tu vas essayer de tenir une porte et ça va être gênant pour tout le monde.", "Ton destin est écrit en Comic Sans sur du papier toilette humide.",
    "Tu vas manger debout au-dessus de l'évier et prétendre que c'est un choix.", "Saturne rétrograde dans ta fierté. Elle en ressort pas.",
    "Les étoiles te regardent avec une sorte de pitié bienveillante. C'est touchant et triste.", "Tu vas répondre \"lol\" à un message sérieux par erreur.",
    "Mercure dit que t'as merdé. T'as merdé.", "Tu vas avoir une discussion très importante avec ton chat. Ton chat s'en bat les reins.",
    "Ton énergie du jour : chaussette mouillée mais qui garde le moral.", "Tu vas faire semblant de pas voir quelqu'un et te prendre un poteau dans la gueule.",
    "L'univers a décidé de te tester. L'univers va être déçu.", "Tu vas recevoir un \"ok\" en réponse à un message de 40 lignes. Les astres compatissent pas vraiment.",
    "Ton avenir ressemble à un Tupperware sans couvercle. Fonctionnel mais incomplet.", "Les planètes indiquent que tu vas te faire remballer. Souris quand même.",
    "Tu vas péter dans ton sommeil et te réveiller. Les étoiles trouvent ça drôle.", "Quelqu'un va te faire une blague de merde et attendre que tu ries. Tu vas rire.",
    "Ton horoscope du jour tient en un mot : mouais.", "Tu vas te lever pour faire quelque chose d'important et oublier quoi en chemin.",
    "Les astres révèlent que t'as la tête dans le cul depuis ce matin. Ressors-la.", "Tu vas regarder ton téléphone à l'envers pendant 3 secondes avant de réaliser.",
    "Mercure est en rétrograde dans ton estime de toi. Ça repart demain. Peut-être.", "Tu vas passer une heure à chercher tes clés. Elles sont dans ta main.",
    "Les étoiles te souhaitent du courage. Elles savent ce qui t'attend.", "Ton karma aujourd'hui : neutre avec des accents de \"t'aurais pu faire mieux\".",
    "Tu vas te convaincre que t'as été productif(ve) alors que t'as rien foutu.", "Les planètes s'alignent dans ta direction pour te dire un grand PFFFFFFFRT.",
    "Tu vas tenter de faire la bise à quelqu'un qui tend la main. Moment cosmique.", "Mercure te dit que t'es con(ne). Mercure a ses jours aussi.",
    "Ton avenir est flou comme une photo prise avec un doigt sur l'objectif.", "Tu vas tomber dans les escaliers en pensant qu'il en restait une marche. Les astres ont prévu les pansements.",
    "Les étoiles forment ce soir la silhouette d'un être qui te ressemble et qui a l'air perdu.", "Tu vas faire une bonne chose aujourd'hui. Par accident. Mais ça compte quand même.",
    "Mercure est en opposition avec ta dignité. La dignité perd aux points.", "Tu vas survivre à cette journée dans un état discutable mais vivant(e). C'est l'essentiel.",
    "Les astres révèlent que Pomni de TADC essaie de s'échapper de ton signe astrologique. Elle peut pas.", "Tu vas passer la journée comme Kinger de TADC : dans un coin, à trembler. Les planètes comprennent.",
    "Ton destin ressemble à un épisode de TADC : coloré, traumatisant, et sans issue claire.", "JDG a reviewé ton avenir. Il lui a mis 2/10. \"C'est de la merde.\"",
    "Springtrap se cache dans ton placard depuis 3 semaines. Évite d'ouvrir.", "Caine de TADC a décidé de ton destin aujourd'hui. Il a lancé un dé. Résultat : chaos.",
    "Tu vas avoir une journée aussi longue qu'un épisode de JDG sur un jeu de merde des années 90.", "Freddy Fazbear te surveille. Il attend juste le bon moment.",
    "Ton aura aujourd'hui : Jax de TADC après sa 3ème mauvaise décision de la journée.", "Tu vas abstraire comme Pomni de TADC mais sans la jolie tenue rose.",
    "FNAF lore a plus de sens que ton planning de la semaine.", "JDG ferait un meilleur boulot que toi aujourd'hui. Et il jouerait à Big Rigs pendant ce temps.",
    "Caine de TADC t'a ajouté au cirque. T'as pas eu le choix. Bienvenue.", "Tu vas te comporter exactement comme Bonnie un soir de panne de courant.",
    "Les planètes forment aujourd'hui la tête de Freddy. Il sourit. C'est pas bon signe.", "Ton énergie du jour : Gangle de TADC qui essaie de tenir le masque de la comédie mais y arrive plus.",
    "JDG résumerait ta journée en deux mots : \"c'est nul\".", "Tu vas te retrouver dans une situation aussi absurde qu'un épisode de TADC et personne te croira.",
    "Bubble de TADC a essayé de lire ton avenir. Elle a explosé avant de finir.", "Springtrap a lu ton horoscope. Il a ri. Ça fait peur.",
    "Tu vas agir exactement comme Jax de TADC : faire une connerie, sourire, recommencer.", "JDG a essayé de finir ta to-do list. Il a abandonné au niveau 1.",
    "Ton chakra du cirque numérique est particulièrement instable aujourd'hui.", "Chica te regarde depuis le fond de la cuisine. Elle a faim. Toi aussi. Mauvaise combinaison.",
    "Les étoiles révèlent que t'es coincé(e) dans le cirque comme tout le monde. Pas d'abstraction aujourd'hui.", "Kinger de TADC a essayé de t'expliquer quelque chose d'important. Il a paniqué avant de terminer.",
    "Ton avenir ressemble au lore de FNAF : trop compliqué, trop long, et t'es sûr(e) que t'as raté un truc.", "JDG a testé ta journée. Note finale : 3/20. \"Y'a un effort mais c'est vraiment pas bon.\"",
    "Zooble de TADC te regarde avec ses yeux détachés. Même iel a l'air inquiet pour toi.", "Les planètes s'alignent comme les animatroniques à 6h du mat. Fuis.",
    "Caine de TADC t'a donné une mission aujourd'hui. T'as pas compris les règles. Bonne chance.", "Tu vas être aussi perdu(e) que Pomni de TADC à son premier jour. Mais t'as pas son énergie.",
    "Les astres forment ce soir la silhouette de Golden Freddy. Dors bien.", "JDG a fait une vidéo sur toi. Elle dure 45 minutes. C'est pas flatteur.",
    "Ton destin est un jeu de merde de 1998 que JDG reviewerait pour rire.", "Tu vas abstraction-run ta vie comme Pomni de TADC mais sans parvenir à t'échapper.",
    "Springtrap est en embuscade dans ta journée. Il est patient. Très patient.", "Caine de TADC a improvisé un jeu pour toi aujourd'hui. Les règles changent toutes les 5 minutes.",
    "JDG te dirait \"c'est comme un mauvais jeu, mais t'es obligé(e) de le finir quand même.\"", "Tu vas passer ta journée comme Kinger de TADC : tout savoir, tout anticiper, paniquer quand même.",
    "Les animatroniques ont voté. T'es éliminé(e). On t'a pas dit de quoi.", "L'univers entier ressemble aujourd'hui à du TADC : coloré, piégé, sans sortie. Bonne journée.",
    "JDG a regardé ton énergie du jour. Il a éteint la caméra sans rien dire.", "Ton signe est en opposition avec Jax de TADC. Jax gagne toujours.",
    "Freddy Fazbear a lu ton horoscope. Il a hoché la tête lentement. C'est inquiétant.", "Les étoiles forment aujourd'hui le sourire de Caine de TADC. T'es dans son jeu maintenant.",
    "JDG te regarde jouer à ta propre vie. Il souffre en silence.", "Gangle de TADC a pleuré pour toi ce matin. Elle savait avant toi.",
    "Les animatroniques ont une réunion ce soir. Ton nom est sur l'ordre du jour.", "Ton destin a été écrit par Caine de TADC un soir de grande forme. C'est dire.",
    "Feldup a commencé un Findings sur ton avenir. Il a arrêté l'idée immédiatement.", "Ton destin fait l'objet d'un épisode de Findings. La vidéo dure 6 heures. Personne la finit.",
    "Feldup enquête sur toi depuis 3 semaines. Il a trouvé des trucs. Il garde ça pour lui, et tant mieux.", "Les astres révèlent que t'es un mystère d'internet que Feldup a classé \"trop bizarre à expliquer\".",
    "Ton aura a été analysée dans un Findings. Conclusion : \"on sait pas trop.\"", "Feldup a trouvé une vidéo de toi sur une plateforme oubliée de 2009. Il enquête.",
    "Les planètes forment aujourd'hui un fil Reddit que Feldup va décortiquer pendant 2 heures.", "Ton histoire a été soumise à Feldup pour un Findings. Il a dit \"trop dark même pour moi.\"",
    "Feldup a tracé les origines de ta malchance jusqu'en 2003. Il comprend pas encore le lien.", "Ton existence est un mystère d'internet que personne a encore vraiment expliqué. Feldup s'y colle.",
    "Les étoiles ont généré un thread 4chan sur ton destin. Feldup en fait un Findings de 5h.", "Feldup a passé 48h à analyser tes décisions de la semaine. Il a conclu que t'es une anomalie statistique.",
    "Ton chakra est documenté dans les archives d'un forum disparu en 2011. Feldup l'a retrouvé.", "Les astres ont classé ta journée dans la catégorie \"phénomène inexpliqué\". Feldup arrive.",
    "Feldup a fait un Findings sur quelqu'un qui te ressemble. T'es sûr(e) que c'était pas toi ?", "Ton avenir est un rabbit hole dont Feldup sort jamais vraiment indemne.",
    "Les planètes révèlent que ton passé internet mériterait un épisode entier de Findings. Commence à paniquer.", "Feldup enquête sur l'origine de ta mauvaise humeur depuis le début de la semaine. Il remonte à loin.",
    "Ton destin a été archivé sur Wayback Machine. Feldup l'a trouvé. Il prépare quelque chose.", "Les étoiles indiquent que t'es au centre d'un mystère que même Feldup peut pas résoudre en moins de 4h.",
    "Feldup a ouvert un nouvel onglet sur toi. Puis un autre. Puis encore un autre. Ça fait 47 onglets.", "Ton aura a laissé des traces sur des forums morts depuis 2007. Feldup les compile.",
    "Les astres révèlent que quelqu'un a posté sur toi sur un forum obscur en 2014. Feldup est sur le coup.", "Feldup a tenté de comprendre ta logique. Il a fait une pause. Il a repris. Il a abandonné.",
    "Ton existence génère le genre de questions que Feldup pose à 2h du mat avant de lancer un Findings.", "Les Archives Regaïennes ont un dossier sur toi. Il est dans les abysses. <@436218312574107658> hésite à y descendre.",
    "<@436218312574107658> a trouvé un ARG qui te concerne. Elle a coupé la caméra sans explication.", "Ton destin a été classé dans les Archives Regaïennes sous la catégorie \"ne pas ouvrir\".",
    "Les étoiles révèlent que t'es quelque part dans un iceberg qu'<@436218312574107658> prépare. T'es dans les abysses.", "Les Archives Regaïennes documentent ton aura depuis 2019. Personne a encore osé regarder jusqu'au bout.",
    "<@436218312574107658> a trouvé un jeu de merde qui te ressemble trait pour trait. Elle a souffert en silence.", "Ton existence est un ARG qu'<@436218312574107658> suit depuis des mois. Elle approche de la fin. Ça l'inquiète.",
    "Les Archives Regaïennes ont archivé tes pires décisions. Le dossier est volumineux.", "Ton destin est dans les abysses d'un iceberg qu'<@436218312574107658> a pas encore eu le courage de finir.",
    "Les Archives Regaïennes te concernent plus que tu le crois. <@436218312574107658> sait. Elle dit rien pour l'instant.", "Un jeu indé bizarre sorti en 2003 raconte exactement ta vie. <@436218312574107658> l'a trouvé. Elle prépare une vidéo.",
    "Les étoiles révèlent que t'es un mystère que les Archives Regaïennes ont classé \"inexpliqué à ce jour\".", "<@436218312574107658> a découvert un forum disparu en 2011 qui parle de toi. Elle descend dans les abysses.",
    "Ton aura a généré un ARG spontané. <@436218312574107658> enquête.", "Les Archives Regaïennes ont trois tomes qui te concernent. Le quatrième est censuré.",
    "<@436218312574107658> a joué à un jeu pourri qui reproduit exactement ta semaine. Elle a mis 2/10. Généreusement.", "Ton destin est l'épisode des Archives Regaïennes qu'<@436218312574107658> a mis le plus de temps à sortir. Elle comprend encore pas tout.",
    "Les étoiles ont généré un mystère d'internet à ton sujet. <@436218312574107658> est dessus depuis 3h du matin.", "T'es dans les abysses d'un iceberg qu'<@436218312574107658> a découvert par accident. Elle regrette un peu.",
    "Les Archives Regaïennes ont documenté ton énergie du jour : \"phénomène non-identifié, à surveiller.\"", "Ton existence entière pourrait faire l'objet d'un ARG. <@436218312574107658> a commencé à tirer les fils. Bonne chance.",
    "Les Archives Regaïennes te souhaitent une bonne journée. Elles savent des trucs. Elles disent rien.", "<@436218312574107658> a trouvé un ARG qui te cible personnellement. Elle prépare une vidéo. T'as pas été prévenu(e).",
    "Ton destin est quelque part dans les abysses d'un iceberg qu'<@436218312574107658> a pas encore osé toucher.", "Les Archives Regaïennes ont un épisode sur toi en post-production. <@436218312574107658> hésite à le sortir.",
    "Tu fais partie d'un mystère d'internet qu'<@436218312574107658> a découvert à 3h du mat. Elle dort plus depuis.", "Ton aura est classée dans les abysses d'un iceberg que personne a encore eu le courage de faire.",
    "<@436218312574107658> a retrouvé une trace de toi sur un site disparu en 2008. Elle creuse.", "Les Archives Regaïennes ont consacré un épisode entier à expliquer pourquoi tu fais des choix pareils. Ça dure 2h.",
    "T'es le genre de mystère qu'<@436218312574107658> tombe dessus par accident et qui lui bouffe 6 mois de recherches.", "Quelqu'un a posté sur toi sur un forum obscur en 2013. <@436218312574107658> l'a trouvé. Elle prend des notes.",
    "Ton existence a été indexée dans un ARG que personne a résolu. <@436218312574107658> est sur le coup.", "Les Archives Regaïennes te concernent plus que tu l'imagines. L'épisode sort quand <@436218312574107658> sera prête.",
    "T'es dans les abysses d'un iceberg qu'<@436218312574107658> a découvert en faisant des recherches sur autre chose.", "<@436218312574107658> a trouvé un jeu de 2001 dont le personnage principal te ressemble de façon troublante.",
    "Ton destin a laissé des traces sur Wayback Machine. <@436218312574107658> les a toutes archivées.", "Un mystère d'internet tourne autour de toi depuis des années. <@436218312574107658> vient juste de s'en rendre compte.",
    "Les Archives Regaïennes ont un épisode qui commence par toi et finit sur quelque chose de bien plus flippant.", "<@436218312574107658> a remonté la trace de ta malchance jusqu'à un événement de 2007 qu'elle peut pas encore expliquer.",
    "T'es quelque part dans les abysses d'un iceberg. <@436218312574107658> te cherche. Elle approche.", "Un ARG lancé en 2015 te ciblait sans que tu le saches. <@436218312574107658> vient de faire le lien.",
    "Les Archives Regaïennes ont documenté ta journée avant même que tu te lèves. <@436218312574107658> était prête.", "Ton passé internet est un rabbit hole qu'<@436218312574107658> explore depuis plusieurs semaines. Elle remonte à loin.",
    "<@436218312574107658> a trouvé un forum de 2010 qui décrit exactement ta personnalité. Elle sait pas quoi en penser.", "T'es le genre de cas que les Archives Regaïennes gardent pour la fin, quand tout le reste a été dit.",
    "Ton aura a été repérée dans un ARG que personne pensait être réel. <@436218312574107658> enquête.", "Les étoiles révèlent que t'es dans les abysses d'un iceberg qu'<@436218312574107658> a intitulé \"à ne pas regarder seul(e)\".",
    "<@436218312574107658> a retrouvé une vidéo YouTube supprimée qui te concerne. Elle a pris des captures d'écran.", "Les Archives Regaïennes ont un épisode sur un mystère qui commence par ta date de naissance. Coïncidence.",
    "T'es référencé(e) dans un wiki d'ARG abandonné depuis 2012. <@436218312574107658> l'a trouvé cette nuit.", "<@436218312574107658> a passé 4h à analyser une image qui te ressemble sur un site que personne visite plus.",
    "Ton destin est documenté quelque part dans les abysses. <@436218312574107658> descend. Elle prend une lampe.", "Les Archives Regaïennes ont failli te consacrer un épisode entier. <@436218312574107658> a jugé que c'était trop tôt.",
    "Un fichier audio trouvé sur un vieux forum contient ton prénom. <@436218312574107658> l'a écouté 12 fois.", "T'es le chapitre final d'un ARG que personne a encore résolu. <@436218312574107658> est à deux pas de la vérité.",
    "Les étoiles révèlent qu'<@436218312574107658> a un dossier sur toi. Il est épais. Elle l'ouvre ce soir.", "Ton existence génère le genre de questions qu'<@436218312574107658> pose à la caméra avec un regard inquiet.",
    "Les Archives Regaïennes ont un épisode qui finit sur toi. <@436218312574107658> a ajouté un avertissement au début.", "T'es dans les abysses d'un iceberg qu'<@436218312574107658> a intitulé \"je préfère pas savoir\" mais elle continue quand même.",
    "<@436218312574107658> a retrouvé un compte abandonné en 2009 dont l'avatar te ressemble. Elle creuse encore.", "Ton destin est le genre de rabbit hole dont <@436218312574107658> sort avec plus de questions que de réponses.",
    "Les Archives Regaïennes ont archivé un mystère qui commence exactement là où ta journée commence.", "<@436218312574107658> a trouvé une trace de toi dans un ARG qu'elle pensait fictif. Elle reconsidère tout.",
    "T'es référencé(e) dans les abysses d'un iceberg qu'<@436218312574107658> appelle \"le dossier qu'on touche pas\".", "Un site Geocities de 2004 parle de toi. <@436218312574107658> l'a trouvé. Elle prend des notes depuis une heure.",
    "Les Archives Regaïennes ont un épisode sur un mystère dont t'es involontairement au centre.", "<@436218312574107658> a découvert que ton prénom apparaît dans un ARG lancé il y a 8 ans. Personne avait fait le lien.",
    "Ton aura est dans les abysses d'un iceberg qu'<@436218312574107658> hésite à finir parce que la fin est trop bizarre.", "Les étoiles révèlent qu'<@436218312574107658> a trouvé quelque chose qui te concerne. Elle prépare ses sources.",
    "T'es le genre de mystère qu'<@436218312574107658> garde pour la fin d'un épisode pour que les gens restent jusqu'au bout.", "Les Archives Regaïennes ont un épisode en cours sur un phénomène inexpliqué. C'est toi. T'étais pas au courant.",
    "<@436218312574107658> a tout trouvé. Elle sait tout. L'épisode sort quand elle aura décidé que t'es prêt(e) à savoir.", "<@511929490964742144> a posté quelque chose dans le salon Shitpost. Personne sait quoi penser. Les astres non plus.",
    "Ton destin a été débattu dans le salon des Modos. Les conclusions sont classifiées.", "<@899733709173948487> a reconnu des patterns FNAF dans ton horoscope. Il a commencé à paniquer.",
    "<@738191002187202630> a regardé ton avenir. Elle a souri. C'est soit très bon soit très mauvais.", "Le pain d'<@436218312574107658> a plus de pouvoirs que toi aujourd'hui. Accepte-le.",
    "<@1070742213635625050> te répond depuis la Corée avec 7h de décalage. Les astres trouvent ça compliqué.", "Jérémy court quelque part dans ton destin. Il s'arrêtera pas. Il s'arrête jamais.",
    "<@704593833421438996> a essayé de coder ton avenir. Il y a un bug. Elle cherche encore.", "<@744217896581857281> a eu une idée géniale à 3h du mat avec ses lunettes de savant fou. Ça te concerne. Fuis.",
    "Les étoiles révèlent que <@511929490964742144> a posté un shitpost qui décrit exactement ta journée. Il savait pas.", "<@731078752708067403> a lancé un débat politique dans ta tête. Tu t'en remets pas depuis ce matin.",
    "<@1263920891264499733> a commenté ton horoscope avec un seul emoji. C'était suffisant.", "La soirée du Bac Blanc a laissé des traces dans l'univers. Les planètes flirtent encore.",
    "<@975959908702888046> a regardé ton aura. Elle a approuvé. Tu sais pas trop quoi en penser.", "<@375746968737021962> a analysé ta situation politique cosmique. Sa conclusion est brillante et légèrement inquiétante.",
    "Ton destin a été posté dans le salon Shitpost. Il a eu 12 réactions 💀.", "Le salon Bots a généré un bug à cause de toi. Cacabot en est partiellement responsable.",
    "<@899733709173948487> a trouvé des similarités entre toi et un animatronique. Il garde ça pour lui pour l'instant.", "<@738191002187202630> existe et les astres sont jaloux. C'est tout ce qu'ils ont à dire aujourd'hui.",
    "<@744217896581857281> a une théorie sur ton avenir. Elle implique un schéma compliqué sur un tableau blanc et beaucoup de fil rouge.", "Le pain d'<@436218312574107658> a été consulté pour lire ton avenir. Il a pas répondu. Comme toujours. C'est déjà une réponse.",
    "Jérémy est passé dans ta journée à toute vitesse. Il a rien dit. Il s'arrête jamais.", "<@731078752708067403> a essayé de débattre avec les étoiles. Les étoiles ont bloqué <@731078752708067403>.",
    "<@704593833421438996> a push du code dans ton destin sans lire les merge requests. Ça explique tout.", "Les planètes révèlent que quelqu'un parle de toi dans le salon des Modos en ce moment.",
    "<@511929490964742144> a shitposté tellement fort aujourd'hui que les astres ont demandé une pause.", "<@375746968737021962> a une opinion très précise sur ta situation. Elle est correcte. Ça t'énerve.",
    "<@1070742213635625050> envoie un message depuis Séoul. Il arrive avec 7h de retard cosmique.", "<@1263920891264499733> a validé ton énergie du jour. Ça suffit. T'as pas besoin d'autre validation.",
    "<@975959908702888046> a regardé ton outfit astral. Elle a apprécié.", "Le salon Cosplay & Outfits a jugé ton aura. Verdict : potentiel, mais à travailler.",
    "La soirée du Bac Blanc est canonique dans l'univers. Les planètes s'en souviennent encore.", "<@744217896581857281> a refait les calculs. Ton destin tient sur 3 post-it et un tableau de corrélations incompréhensible.",
    "<@899733709173948487> a identifié ton signe comme un personnage de TADC. Il refuse de dire lequel.", "Le pain d'<@436218312574107658> a bougé tout seul cette nuit. Les astres notent l'événement sans commenter.",
    "Jérémy court encore. Il a pas de destination. Il a pas besoin d'en avoir.", "<@704593833421438996> a debuggé ton karma. Elle a trouvé 7 erreurs. Elle corrige dans l'ordre.",
    "<@738191002187202630> a souri en pensant à toi ce matin. Les étoiles ont eu chaud.", "<@731078752708067403> a lancé un débat sur le meilleur système électoral dans le fil de ton destin. Tout le monde souffre.",
    "<@511929490964742144> a posté le gif Markiplier au bon moment. Comme toujours. Les astres saluent.", "<@375746968737021962> a commenté ta situation en trois phrases. C'était plus éclairant que cet horoscope entier.",
    "Ton destin ressemble au salon Shitpost : dense, incompréhensible, mais vivant.", "<@1070742213635625050> a envoyé un message à minuit heure coréenne pour te dire que ça allait aller. Il avait raison.",
    "<@975959908702888046> a une vision très précise de ton avenir. Elle la partage pas. Elle sourit juste.", "<@1263920891264499733> a regardé ton horoscope. Il a dit \"same\". C'est la réponse la plus juste.",
    "Le salon des Modos a voté sur quelque chose qui te concerne. Le résultat est secret.", "<@744217896581857281> a inventé un mot pour décrire ton énergie du jour. Personne comprend ce mot. <@744217896581857281> non plus.",
    "<@899733709173948487> a croisé ton nom dans un wiki FNAF. Il enquête.", "Le mariage de <@738191002187202630> et <@436218312574107658> a rééquilibré les forces cosmiques pour un moment. Les planètes s'en remettent encore.",
    "Cacabot a tout vu. Cacabot dit rien. Cacabot sait.", "Les étoiles ont posté dans le salon Shitpost. <@511929490964742144> a répondu plus vite qu'elles.",
    "Ton karma a été merge request par <@704593833421438996>. Elle attend la review depuis 3 jours.", "<@744217896581857281> a une théorie sur l'origine du pain d'<@436218312574107658>. Elle implique des dimensions parallèles et un four à micro-ondes.",
    "<@899733709173948487> a reconnu ton pattern de comportement dans le lore de FNAF Security Breach. Il est inquiet.", "<@738191002187202630> a existé aujourd'hui. Les astres ont trouvé ça injustement bien.",
    "<@375746968737021962> a expliqué ta situation géopolitique cosmique en 4 minutes. C'était fascinant et légèrement déprimant.", "Jérémy est passé. Il repassera. Il s'arrêtera toujours pas.",
    "Le pain d'<@436218312574107658> a regardé dans ta direction ce matin. T'as rien remarqué. C'est peut-être mieux.", "<@731078752708067403> a lancé un débat sur la proportionnelle dans le fil de tes rêves. Tu t'es réveillé(e) épuisé(e).",
    "<@511929490964742144> a shitposté quelque chose qui ressemble exactement à ton horoscope. C'était involontaire. Ou pas.", "<@1070742213635625050> a validé ton énergie depuis Séoul avec un pouce en l'air. Il savait pas pourquoi. Il avait quand même raison.",
    "<@1263920891264499733> a regardé ton destin. Il a haussé les épaules avec classe. C'est suffisant.", "<@975959908702888046> a commenté ton aura. Elle a dit \"cute\". Les astres rougissent.",
    "<@704593833421438996> a refactorisé ton avenir. C'est plus propre mais y a toujours un bug inexpliqué ligne 247.", "Le salon des Modos a un thread entier sur toi. Il est archivé. Il est long.",
    "<@744217896581857281> a dessiné un schéma de ton destin sur un tableau. Il y a des flèches partout. Aucune ne pointe dans la même direction.", "Les étoiles révèlent que Cacabot t'a observé(e) toute la semaine. Cacabot prend des notes.",
    "<@899733709173948487> a fait le lien entre ton signe et un personnage de TADC. Il garde l'info pour lui mais son regard dit tout.", "<@738191002187202630> a ri d'un truc aujourd'hui. L'univers entier a trouvé ça sympa.",
    "La soirée du Bac Blanc a changé la trajectoire des planètes. Elles flirtent encore entre elles depuis.", "<@375746968737021962> a prédit ta journée avec une précision troublante. Il a précisé que c'était \"juste de la logique\".",
    "<@511929490964742144> a posté le gif Markiplier exactement quand il fallait. Les astres notent l'excellence du timing.", "Ton destin a été debug par <@704593833421438996> à 2h du mat. Elle a trouvé l'erreur. Elle l'a pas corrigée. Elle dort.",
    "<@744217896581857281> a réfléchi à ton avenir avec ses lunettes de savant fou. Elle a conclu quelque chose d'important qu'elle a aussitôt oublié.", "Le pain d'<@436218312574107658> a disparu cette nuit. Il est revenu ce matin. Personne a posé de questions.",
    "Jérémy a croisé ton destin en courant. Il a pas ralenti. Il ralentit jamais.", "<@1070742213635625050> t'a envoyé un message depuis un café à Séoul. Il dit que t'inquiète pas. Il a l'air sûr de lui.",
    "<@731078752708067403> a lancé un débat sur le vote obligatoire dans ta to-do list. T'as rien demandé.", "<@975959908702888046> a validé ton outfit astral sans hésiter. C'est le meilleur retour que t'auras aujourd'hui.",
    "<@1263920891264499733> a lu ton horoscope et a dit \"mood\". C'est la critique la plus juste possible.", "Le salon Cosplay & Outfits a jugé l'esthétique de ton aura. Verdict : iconique mais perfectible.",
    "<@899733709173948487> a trouvé un easter egg FNAF dans ton horoscope. Il screenshot tout.", "Les planètes révèlent que quelqu'un spam le salon Bots pour interagir avec Cacabot depuis 20 minutes. C'est pour toi.",
    "<@704593833421438996> a push en prod ton avenir sans staging. Les conséquences sont en cours.", "<@744217896581857281> a inventé un mot pour ton énergie cosmique. Elle l'a écrit sur un post-it. Le post-it a disparu.",
    "<@738191002187202630> a souri et ça a suffi à stabiliser l'axe de rotation de la Terre aujourd'hui.", "<@375746968737021962> a une analyse politique de ton horoscope qui tient en 6 points. Le point 4 te concerne particulièrement.",
    "<@511929490964742144> a posté quelque chose dans le Shitpost qui était tellement absurde que les étoiles ont clignoté.", "Le pain d'<@436218312574107658> a émis un son cette nuit. Les astres ont décidé de ne pas enquêter.",
    "Jérémy a traversé ton salon en courant pendant que tu dormais. Les traces sont là si tu cherches bien.", "<@731078752708067403> a essayé de débattre avec Cacabot. Cacabot a répondu \"Feur\". <@731078752708067403> a pas su quoi dire.",
    "<@1070742213635625050> a envoyé une photo depuis un marché coréen. Elle était floue. Les astres pensent que c'était un signe.", "<@975959908702888046> a regardé ton destin avec un sourire connaisseur. Elle sait des trucs. Elle dit rien.",
    "<@1263920891264499733> a existé aujourd'hui. Les planètes trouvent ça cool.", "<@704593833421438996> a créé une fonction pour gérer ton karma. Elle est élégante. Elle marche pas encore tout à fait.",
    "<@744217896581857281> a eu une révélation sur le pain d'<@436218312574107658> à 4h du mat. Elle l'a notée. L'écriture est illisible.", "Les étoiles ont posté dans le salon Bots. Cacabot leur a répondu \"Feur\". Ambiance.",
    "<@899733709173948487> a regardé ton destin comme il regarde un épisode de TADC : avec intensité et une légère anxiété.", "<@738191002187202630> et <@436218312574107658> ont fondamentalement rééquilibré les forces de l'univers le soir du Bac Blanc. Les planètes en parlent encore.",
    "<@375746968737021962> a conclu que ta situation est \"objectivement intéressante d'un point de vue politique\". Il a pas tort.", "<@511929490964742144> a shitposté quelque chose ce matin qui prédit exactement ce qui va t'arriver aujourd'hui. Il le sait pas.",
    "Le salon des Modos a un vote en cours te concernant. Le résultat sera annoncé quand t'es pas là.", "<@744217896581857281> a refait ses calculs. Ton destin nécessite encore plus de fil rouge et un deuxième tableau blanc.",
    "Le pain d'<@436218312574107658> a été aperçu à deux endroits en même temps ce matin. Les astres prennent note.", "Jérémy court encore. Il a jamais commencé. Il arrêtera jamais. C'est son état naturel.",
    "<@704593833421438996> a ouvert une issue GitHub sur ton avenir. Elle est intitulée \"comportement inattendu\". Elle est ouverte depuis longtemps.", "<@1070742213635625050> a regardé l'heure à Séoul et s'est dit que toi t'étais sûrement encore debout à faire des bêtises. Il avait raison.",
    "<@731078752708067403> a tenté de convaincre les astres de voter autrement. Les astres ont fermé l'onglet.", "<@975959908702888046> a dessiné ton aura de mémoire. C'est étonnamment précis et légèrement flatteur.",
    "<@1263920891264499733> a validé ton existence d'un regard. C'est amplement suffisant.", "<@899733709173948487> a tracé des parallèles entre ton horoscope et le lore de FNAF Sister Location. Il est troublé.",
    "Les étoiles révèlent que le salon Shitpost te concerne plus que tu le crois ce soir.", "Cacabot a tout documenté. Cacabot garde les archives. Cacabot sourit pas parce que Cacabot a pas de visage. Mais Cacabot sait.",
    "<@375746968737021962> a regardé ta journée d'un œil analytique et a conclu que \"franchement c'est pas si mal dans l'absolu\".", "<@744217896581857281> a une nouvelle théorie. Elle implique le pain d'<@436218312574107658>, Jérémy, et un événement cosmique de 2019. Le schéma est complexe.",
    "<@511929490964742144> a rien posté depuis 3h. Les astres sont inquiets. C'est pas normal.", "<@738191002187202630> a existé avec une grâce particulière aujourd'hui. L'univers a pris bonne note.",
    "<@704593833421438996> a refactorisé le code source de ton destin. C'est plus lisible. Y a toujours un warning qu'elle ignore.", "Le pain d'<@436218312574107658> a regardé Jérémy courir. Il a rien dit. Il dit jamais rien. C'est ça qui fait peur.",
    "<@731078752708067403> a proposé une réforme du système cosmique. Les planètes ont dit non. <@731078752708067403> a relancé le débat.", "<@1070742213635625050> a envoyé un voice message depuis la Corée. Il dure 4 minutes. L'info principale est à la toute fin.",
    "<@975959908702888046> a regardé dans ta direction avec une expression que personne a réussi à déchiffrer. Les astres non plus.", "<@1263920891264499733> a commenté ton destin avec un émoji. Un seul. C'était le bon.",
    "<@899733709173948487> a fait une liste de tous les personnages TADC et FNAF qui te ressemblent. La liste est longue.", "Les Archives Regaïennes ont un épisode en préparation sur le pain d'<@436218312574107658>. <@436218312574107658> hésite encore à sortir les vraies conclusions.",
    "Toy Bonnie a regardé ton horoscope. Il a souri. C'est pire que quand il sourit pas.", "Pomni de TADC a tenté de s'échapper de ton signe astrologique. Elle a couru en rond pendant 3h.",
    "Les animatroniques ont tenu une réunion sur ton cas. Freddy a pris la parole en dernier. C'est jamais bon signe.", "Jax de TADC a sabordé ton planning de la journée par pur plaisir. Il regrette pas.",
    "Withered Bonnie te cherche depuis ce matin. Il a pas de visage mais il te trouvera quand même.", "Caine de TADC a créé un mini-jeu spécialement pour toi. Les règles sont inexistantes. Bonne chance.",
    "Golden Freddy est assis dans ton salon depuis une semaine. Tu l'as pas encore vu.", "Gangle de TADC pleure pour toi depuis ce matin. Elle sait ce qui t'attend. Elle peut rien faire.",
    "Les Marionettes de FNAF ont un dossier sur toi. Il est dans la pizzeria. La pizzeria est hantée.", "Kinger de TADC a tout anticipé pour ta journée. Il a paniqué avant même que ça commence.",
    "Ennard se balade dans tes canalisations depuis jeudi. Les astres suggèrent d'éviter les sous-sols.", "Zooble de TADC te regarde depuis l'autre côté de la pièce. Ses yeux sont détachés. Ils te suivent quand même.",
    "Springtrap a lu ton horoscope deux fois. Il a pris des notes. Ses notes sont illisibles mais nombreuses.", "Bubble de TADC a essayé de t'expliquer ton destin. Elle a explosé à mi-chemin. Message non transmis.",
    "Glamrock Freddy a essayé de te protéger aujourd'hui. Il a glitché au mauvais moment. Désolé.", "Ragatha de TADC t'a encouragé(e) ce matin avec un grand sourire. Elle souffre en silence. Comme toi.",
    "Ballora danse quelque part dans ton avenir. T'entends la musique si tu écoutes bien. T'as pas envie d'écouter.", "Jax de TADC a parié sur ta journée avec Caine de TADC. Jax a gagné. C'est mauvais signe pour toi.",
    "Circus Baby te regarde depuis les coulisses de ta vie. Elle attend le bon moment depuis longtemps.", "Pomni de TADC a essayé de documenter ta journée pour avoir un repère dans la réalité. Elle a abandonné.",
    "Les Nightguards de FNAF ont refusé le poste pour surveiller ta nuit. Même eux ont des limites.", "Caine de TADC a ajouté un obstacle supplémentaire dans ton planning. Il trouve ça drôle. Il a pas tort.",
    "Vanny court quelque part derrière toi. Lentement. Régulièrement. Depuis ce matin.", "Kaufmo de TADC a abstrait avant de pouvoir te dire ce qui t'attendait aujourd'hui. Message perdu.",
    "L'animatronique de la Pizzeria a bougé d'un centimètre cette nuit. Les caméras ont tout vu. Toi non.", "Tu vas te chier dessous mentalement avant même d'arriver à midi.",
    "Les astres révèlent que t'as une collection de trucs inutiles que tu gardes \"au cas où\". T'en auras besoin jamais.", "Ton aura sent le Monster Energy et les regrets.",
    "Tu vas perdre une game à cause d'un lag et blâmer ta connexion. C'était pas la connexion.", "Les étoiles révèlent que t'as encore des notifications non lues depuis 2019.",
    "Ton destin ressemble à un Creepypasta écrit par un gamin de 12 ans à 3h du mat. C'est toi le gamin.", "Tu vas mourir dans un jeu en mode \"easy\" et prétendre que le jeu est mal équilibré.",
    "Les planètes révèlent que t'as encore Minecraft installé. Tu joues plus mais tu désinstalles pas. C'est important.", "Ton chakra est bloqué par 47 onglets ouverts depuis 3 semaines.",
    "Tu vas relire un Creepypasta que t'avais adoré à 13 ans et réaliser qu'il était nul. C'est douloureux.", "Les étoiles révèlent que quelqu'un t'a dit \"skill issue\" aujourd'hui et avait raison.",
    "Ton avenir ressemble à un wiki abandonné sur un jeu que plus personne joue.", "Tu vas tomber dans un trou dans Minecraft et perdre ton stuff du nerf. Les astres compatissent pas.",
    "Les planètes révèlent que ton humeur du jour c'est \"NPC en attente de son trigger\".", "Tu vas lire le lore d'un jeu vidéo pendant 2h au lieu de jouer au jeu.",
    "Ton destin a été spoilé sur Reddit par quelqu'un avec zéro karma.", "Les étoiles révèlent que t'as encore une save de jeu de 2017 que tu reprends jamais mais supprime jamais.",
    "Tu vas te péter les doigts de pied sur un meuble et jurer en anglais par réflexe.", "Ton aura est le niveau tutoriel d'un jeu qui explique trop et trop longtemps.",
    "Les planètes ont tenté de te speedrun. Elles ont fait Any% parce que t'es trop compliqué(e) en 100%.", "Tu vas lire \"press F to pay respects\" dans ta tête dans un moment de deuil réel.",
    "Les astres révèlent que t'as un personnage préféré dans un jeu que personne d'autre a joué.", "Ton destin est un easter egg caché dans un jeu AA de 2009 que personne a trouvé sauf toi.",
    "Tu vas dire \"c'est comme dans [jeu vidéo]\" dans une conversation sérieuse et perdre tout le monde.", "Les étoiles révèlent que t'as une lore theory sur un jeu que tu gardes pour toi parce que personne comprendrait.",
    "Ton chakra du jour : chargement infini avec une barre de progression qui recule parfois.", "Tu vas craft quelque chose d'inutile dans un crafting game juste pour voir. Ça prend 3h.",
    "Les planètes révèlent que quelqu'un quelque part joue un personnage qui te ressemble dans un RPG. Il souffre.", "Ton avenir est un DLC pas encore annoncé. Il sortira en retard. Il coûtera trop cher.",
    "Tu vas avoir une théorie sur un jeu vidéo qui est en fait complètement correcte mais invérifiable.", "Les étoiles révèlent que t'as dit \"je joue juste encore 5 minutes\" il y a 4 heures.",
    "Ton énergie du jour : personnage secondaire qui mériterait son propre arc narratif.", "Tu vas mourir d'une façon stupide dans un jeu et regarder l'écran en silence pendant 10 secondes.",
    "Les planètes révèlent que t'as une playlist \"pour travailler\" qui contient que des OST de jeux vidéo.", "Ton destin ressemble à un jeu avec un ending secret que 3 personnes ont trouvé et que personne croit.",
    "Tu vas chercher sur Google comment faire quelque chose dans un jeu et tomber sur un forum de 2007 avec une réponse de \"lol bonne chance\".", "Les étoiles révèlent que t'as une peluche sur ton bureau que tu gardes depuis l'enfance et que tu touches pas mais qui doit rester là.",
    "Ton aura est un personnage qu'on joue pas au début mais qu'on unlock après 40h de jeu.", "Tu vas essayer de faire un truc stylé dans un jeu et te planter devant quelqu'un. Les astres ont regardé.",
    "Les planètes révèlent que t'as pleuré pour un personnage de jeu vidéo que t'admets pas avoir pleuré.", "Ton destin est une quête secondaire que le jeu t'oblige pas à faire mais que tu fais quand même à 100%.",
    "Les étoiles révèlent que t'as une théorie sur le lore d'un jeu qui relie tout parfaitement. Personne l'a écoutée.", "Ton chakra est le petit bruit de notification d'un jeu mobile que t'as désinstallé mais dont tu te souviens encore.",
    "Tu vas citer une réplique d'un jeu vidéo en pensant que c'est drôle. C'est drôle. Pour toi.", "Les planètes révèlent que ton personnage préféré est celui que tout le monde déteste sauf toi.",
    "Ton avenir ressemble à un jeu que les développeurs ont abandonné mais qui a une communauté de fans dévoués.", "Tu vas faire un saut de la foi dans un jeu et tomber dans le vide. Les astres avaient vu le bord.",
    "Les étoiles révèlent que t'as une opinion très tranchée sur quel jeu méritait plus de succès et tu la défends encore.", "Ton destin est un glitch de jeu vidéo que les développeurs ont jamais patché parce qu'ils savaient pas qu'il existait.",
    "Tu vas avoir les mains moites pendant un boss fight et prétendre que c'est la chaleur.", "Les planètes révèlent que t'as un skin dans un jeu que tu gardes depuis des années et que tu portes jamais parce qu'il est \"trop bien pour être gaspillé\".",
    "Ton aura est le bruit d'un floppy disk qui charge. Lentement. Mais il charge.", "Tu vas googler les symptômes d'une maladie de jeu vidéo dans la vraie vie. Juste pour voir.",
    "Les étoiles révèlent que quelque part t'as encore un Tamagotchi mort que t'as pas eu le courage de relancer.", "Ton destin est une quête buggée que tu peux plus compléter mais qui reste dans ton journal.",
    "Tu vas essayer d'expliquer le lore de FNAF à quelqu'un. Tu vas perdre la personne au bout de 3 minutes.", "Les planètes révèlent que ton cerveau charge ses ressources en arrière-plan depuis ce matin. Il finira ce soir peut-être.",
    "Ton énergie du jour : touche Echap appuyée trop longtemps pendant un cutscene obligatoire.", "Tu vas avoir un déclic sur quelque chose d'important exactement 5 secondes trop tard. Les astres avaient l'heure.",
    "Les étoiles révèlent que t'as un dossier de screenshots de moments de jeu que tu montreras jamais à personne.", "Ton avenir est un jeu en accès anticipé depuis 2018. Il sortira. Promis.",
    "Tu vas perdre un objet important dans la vraie vie et avoir le réflexe de chercher dans ton inventaire.", "Les planètes révèlent que ton chat t'a regardé jouer avec un mépris total et assumé.",
    "Ton destin est une fanfic de 200 chapitres sur un jeu de niche que tu suis depuis 3 ans.", "Tu vas entendre une musique et réaliser que c'est une OST de jeu vidéo que tu reconnaissais pas consciemment depuis des années.",
    "Les étoiles révèlent que t'as un tier list de trucs complètement inutiles quelque part. Elle est précise. Elle est juste.", "Ton chakra est un personnage en T-pose au loin qui disparaît quand tu t'approches.",
    "Tu vas relire des anciens messages et trouver une version de toi que tu comprends plus du tout.", "Les planètes révèlent que t'as une opinion très précise sur le meilleur ending d'un jeu et c'est pas le canon.",
    "Ton avenir est un ARG lancé par des devs d'un jeu indé qui ont jamais révélé si c'était intentionnel.", "Tu vas expliquer pourquoi un jeu est sous-estimé pendant 20 minutes à quelqu'un qui demandait juste le titre.",
    "Les étoiles révèlent que quelqu'un quelque part speed run ta vie en Any%. Il est déjà à la moitié.", "Ton destin est un mod de jeu vidéo installé par quelqu'un d'autre qui change tout sans prévenir.",
    "Les planètes te souhaitent bonne chance. Elles savent que t'en auras besoin. Elles savent que ça changera rien.", "<@390539577833684994> a composé une chanson sur ton destin. Elle est belle. Elle fait peur.",
    "<@390539577833684994> a écouté ton aura. Elle en a fait un son ambient. C'est troublant et magnifique.", "<@390539577833684994> ressemble tellement à Feldup que les planètes font encore la différence difficilement.",
    "<@390539577833684994> a produit le générique de ta journée. Il est court mais intense.", "Les étoiles révèlent que <@390539577833684994> a composé quelque chose qui te correspond exactement. Elle savait pas que c'était pour toi.",
    "<@390539577833684994> a regardé ton horoscope et a dit \"j'en ferai un sample\". Les astres sont flattés.", "Les planètes révèlent que <@390539577833684994> est simplement là, et ça suffit à améliorer la journée de tout le monde.",
    "<@390539577833684994> a produit le son de ton destin. Il est lo-fi, mélancolique, et étrangement beau.", "<@390539577833684994> existe et les astres trouvent ça vraiment bien pour tout le monde.",
    "<@899733709173948487> a analysé ton signe astrologique pendant 3h. Il a trouvé un pattern. Il dit rien pour l'instant.", "Les astres révèlent que <@899733709173948487> a classé ton signe dans son tier list Nintendo. T'es pas en S tier. Désolé.",
    "<@899733709173948487> a fait le lien entre ton comportement et un boss de jeu Nintendo. Il sait comment te battre.", "Les planètes révèlent que <@899733709173948487> a remarqué quelque chose dans ta façon d'agir que personne d'autre a vu. Il note tout.",
    "<@899733709173948487> a trouvé un easter egg caché dans ton destin. Il hésite à te le dire depuis 3 semaines.", "Les étoiles révèlent que <@899733709173948487> a une théorie sur toi. Elle est précise, documentée, et légèrement inquiétante.",
    "<@899733709173948487> perçoit des choses dans ton aura que les autres ratent complètement. Il observe en silence.", "Les astres indiquent que <@899733709173948487> a comparé ta journée à un niveau de jeu Nintendo. T'es bloqué au même endroit depuis un moment.",
    "<@899733709173948487> a détecté un comportement récurrent chez toi. Il l'a mis dans un spreadsheet. Il analyse encore.", "Les planètes révèlent que <@899733709173948487> sait exactement ce que tu vas faire ensuite. Il attendait que tu arrives là.",
    "<@511929490964742144> t'a envoyé un message en anglais mal orthographié. T'as mis 10 minutes à comprendre. C'était juste \"hello\".", "Les astres révèlent que <@511929490964742144> a commenté ton horoscope en anglais. \"ur futur is ded lmao\". Les planètes traduisent pas.",
    "<@511929490964742144> a prédit ta journée en trois mots anglais incorrects. C'était plus précis que cet horoscope entier.", "Les étoiles révèlent que <@511929490964742144> t'a envoyé un shitpost en \"english\". T'as compris à moitié. C'était suffisant.",
    "<@511929490964742144> a écrit quelque chose sur toi dans le salon shitpost. En anglais approximatif. Tout le monde a réagi avec 💀.", "Les planètes révèlent que <@511929490964742144> t'a dit \"ur a weirdo\" ce matin. C'était un compliment. Il confirme.",
    "<@511929490964742144> a résumé ton destin en un tweet mal écrit en anglais. Il a raison sur tout.", "Les astres révèlent que <@511929490964742144> pense à toi en ce moment. Il va poster quelque chose. En anglais. Avec des fautes. Sur toi.",
    "<@511929490964742144> a lu ton horoscope et a répondu \"gg ez\". Les étoiles sont d'accord.", "Les planètes révèlent que <@511929490964742144> a une opinion sur toi. Elle tient en 4 mots anglais mal orthographiés. Elle est juste."

    ];
    const seed = dateKey * 100 + signIndex;
    const idx = Math.floor(seedRandom(seed) * horoscopes.length);
    return horoscopes[idx];
}

function buildHoroscopeEmbed() {
    const now = new Date();
    const dateKey = now.getFullYear() * 10000 + (now.getMonth() + 1) * 100 + now.getDate();
    const dateStr = now.toLocaleDateString('fr-FR', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });

    const signes = [
        { nom: 'Bélier', emoji: '♈' }, { nom: 'Taureau', emoji: '♉' }, { nom: 'Gémeaux', emoji: '♊' },
        { nom: 'Cancer', emoji: '♋' }, { nom: 'Lion', emoji: '♌' }, { nom: 'Vierge', emoji: '♍' },
        { nom: 'Balance', emoji: '♎' }, { nom: 'Scorpion', emoji: '♏' }, { nom: 'Sagittaire', emoji: '♐' },
        { nom: 'Capricorne', emoji: '♑' }, { nom: 'Verseau', emoji: '♒' }, { nom: 'Poissons', emoji: '♓' },
        { nom: 'Loutre', emoji: '🦦' },
    ];

    const description = signes.map((s, i) => `${s.emoji} **${s.nom}**\n${getHoroscopeForSign(i, dateKey)}`).join('\n\n');

    return new EmbedBuilder()
        .setColor(0x2c2f33)
        .setTitle('🔮 Horoscope du jour')
        .setDescription(description)
        .setThumbnail('https://cdn.discordapp.com/attachments/1128032964924670053/1505637234596905080/color-replaced.png')
        .setFooter({ text: `📅 ${dateStr.charAt(0).toUpperCase() + dateStr.slice(1)}` });
}

async function execute(message, client, response) {
    if (!response?.needsHoroscope) return;

    const args = message.content.trim().split(/\s+/);
    const forcedChannelId = args[1] && message.author.id === '436218312574107658' ? args[1] : null;
    let targetChannel = message.channel;

    if (forcedChannelId) {
        try {
            targetChannel = await client.channels.fetch(forcedChannelId);
            if (!targetChannel) return message.reply('Salon introuvable.');
        } catch (e) {
            return message.reply('Salon introuvable.');
        }
    }

    const embed = buildHoroscopeEmbed();

    // On gère ici l'envoi selon si c'est un salon forcé ou non
    if (forcedChannelId) {
        const titres = [
            '# HOROSCOPE DU JOUR 🔮',
            "# L'ORACLE A PARLÉ 🔮",
            '# LES ASTRES ONT PARLÉ 🔮',
            '# LES ÉTOILES ONT PARLÉ 🔮',
            "# L'UNIVERS NOUS ENVOIE SES SIGNES 🔮",
        ];
        const titre = titres[Math.floor(Math.random() * titres.length)];
        await targetChannel.send({ content: titre, embeds: [embed] });
    } else {
        await targetChannel.send({ embeds: [embed] });
    }
}

module.exports = { getHoroscopeForSign, buildHoroscopeEmbed, execute };